---
deployment:
  tasks:
    - export PATH=$HOME/.nvm/versions/node/$(node -v)/bin:$PATH
    - echo "Installing dependencies..."
    - pnpm install
    - echo "Building TypeScript..."
    - pnpm run build
    - echo "Restarting bot via PM2..."
    - pm2 restart aaa-store-bot || pm2 start dist/index.js --name aaa-store-bot